name: humble

on:
  push:
    branches:
      - humble-devel
  pull_request:
    branches:
      - humble-devel
  schedule:
    - cron: "0 7 * * 1"

jobs:
  ROS2:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2 environment
        uses: ros-tooling/setup-ros@0.7.9
        with:
          ros-distro: humble

      - name: Build ROS 2 package
        uses: ros-tooling/action-ros-ci@0.3.13
        with:
          package-name: go2_description
          target-ros2-distro: humble
